pipelines:
  default:
    - step:
        name: Python3.12
        image: python:3.12
        script:
          - pip install .
          - python colossus/tests/run_tests.py  
    - step:
        name: Python3.11
        image: python:3.11
        script:
          - pip install .
          - python colossus/tests/run_tests.py
    - step:
        name: Python3.10
        image: python:3.10
        script:
          - pip install .
          - python colossus/tests/run_tests.py
    - step:
        name: Python3.9
        image: python:3.9
        script:
          - pip install .
          - python colossus/tests/run_tests.py          
    - step:
        name: Python2.7
        image: python:2.7
        script:
          - pip install .
          - python colossus/tests/run_tests.py