pipelines:
  default:
    - step:
        name: Python3.7
        image: python:3.7
        script:
          - pip install numpy scipy
          - python setup.py install
          - python colossus/tests/run_tests.py  
    - step:
        name: Python3.6
        image: python:3.6
        script:
          - pip install numpy scipy
          - python setup.py install
          - python colossus/tests/run_tests.py
    - step:
        name: Python2.7
        image: python:2.7
        script:
          - pip install numpy scipy
          - python setup.py install
          - python colossus/tests/run_tests.py